CREATE TABLE "mytable" (
  "-- ======================= NULL VALIDATION ===============================" text NULL
);

INSERT INTO "mytable" ("-- ======================= NULL VALIDATION ===============================")
VALUES
('-- ====================== POSTGRES SQL ================================='),
('DO $$'),
('DECLARE'),
('r RECORD;'),
('v_sql TEXT;'),
('BEGIN'),
('-- 1. Create temporary table explicitly'),
('CREATE TEMP TABLE IF NOT EXISTS pg_null_matrix ('),
('table_name TEXT'),
('column_name TEXT'),
('null_count BIGINT'),
(');'),
('TRUNCATE TABLE pg_null_matrix;'),
('FOR r IN'),
('SELECT c.table_schema'),
('FROM information_schema.columns c'),
('JOIN information_schema.tables t ON c.table_name = t.table_name AND c.table_schema = t.table_schema'),
('WHERE t.table_type = ''BASE TABLE'''),
('AND c.is_nullable = ''YES'''),
('AND (c.table_schema || ''_'' || c.table_name) IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''errorlog'''),
(')'),
('LOOP'),
('-- FIXED: Ensured format placeholders safely build schema.table and filter by column correctly'),
('v_sql := format(''INSERT INTO pg_null_matrix SELECT %L'),
('r.table_name'),
('EXECUTE v_sql;'),
('END LOOP;'),
('END $$;'),
('SELECT table_name AS TableName'),
('FROM pg_null_matrix'),
('WHERE null_count > 0'),
('ORDER BY table_name'),
('DROP TABLE IF EXISTS pg_null_matrix;'),
('-- ================================ MY SQL =================================================='),
('DROP PROCEDURE IF EXISTS GetExactNullCounts;'),
('DELIMITER $$'),
('CREATE PROCEDURE GetExactNullCounts(IN db_name VARCHAR(255))'),
('BEGIN'),
('DROP TABLE IF EXISTS tmp_null_counts;'),
('CREATE TEMPORARY TABLE tmp_null_counts ('),
('table_name VARCHAR(255)'),
('column_name VARCHAR(255)'),
('null_count BIGINT'),
(');'),
('BEGIN'),
('DECLARE done INT DEFAULT FALSE;'),
('DECLARE t_name VARCHAR(255);'),
('DECLARE c_name VARCHAR(255);'),
(NULL),
('DECLARE cur CURSOR FOR'),
('SELECT TABLE_NAME'),
('FROM INFORMATION_SCHEMA.COLUMNS'),
('WHERE TABLE_SCHEMA = db_name'),
('AND IS_NULLABLE = ''YES'''),
('AND TABLE_NAME IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''errorlog'''),
(');'),
(NULL),
('DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;'),
('OPEN cur;'),
('read_loop: LOOP'),
('FETCH cur INTO t_name'),
('IF done THEN'),
('LEAVE read_loop;'),
('END IF;'),
('SET @sql = CONCAT('),
('''INSERT INTO tmp_null_counts '''),
('''SELECT \'''''),
('''FROM `'''),
(');'),
(NULL),
('PREPARE stmt FROM @sql;'),
('EXECUTE stmt;'),
('DEALLOCATE PREPARE stmt;'),
('END LOOP;'),
('CLOSE cur;'),
('END;'),
('SELECT table_name AS TableName'),
('FROM tmp_null_counts'),
('WHERE null_count > 0'),
('ORDER BY table_name'),
(NULL),
('DROP TABLE IF EXISTS tmp_null_counts;'),
('END$$'),
('DELIMITER ;'),
('-- Execute call string:'),
('CALL GetExactNullCounts(''adventureworks2025'');'),
('-- ============================= MS SQL SERVER ========================================='),
('CREATE OR ALTER PROCEDURE GetExactNullCounts'),
('@db_name SYSNAME'),
('AS'),
('BEGIN'),
('SET NOCOUNT ON;'),
('IF OBJECT_ID(''tempdb..#tmp_null_counts'') IS NOT NULL'),
('DROP TABLE #tmp_null_counts;'),
('CREATE TABLE #tmp_null_counts ('),
('TableName SYSNAME'),
('ColumnName SYSNAME'),
('NullCount BIGINT'),
(');'),
('DECLARE @t_name SYSNAME;'),
('DECLARE @c_name SYSNAME;'),
('DECLARE @sql NVARCHAR(MAX);'),
('DECLARE cur CURSOR FOR'),
('SELECT TABLE_NAME'),
('FROM INFORMATION_SCHEMA.COLUMNS'),
('WHERE TABLE_CATALOG = @db_name'),
('AND IS_NULLABLE = ''YES'''),
('AND TABLE_NAME IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''production_scrapreason'''),
('''production_location'''),
('''sales_salesreason'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''awbuildversion'''),
(');'),
('OPEN cur;'),
('FETCH NEXT FROM cur INTO @t_name'),
('WHILE @@FETCH_STATUS = 0'),
('BEGIN'),
('SET @sql = N'''),
('INSERT INTO #tmp_null_counts (TableName'),
('SELECT'),
('@tbl'),
('@col'),
('COUNT(*)'),
('FROM '' + QUOTENAME(@db_name) + ''.dbo.'' + QUOTENAME(@t_name) + '''),
('WHERE '' + QUOTENAME(@c_name) + '' IS NULL;'';'),
('EXEC sp_executesql'),
('@sql'),
('N''@tbl sysname'),
('@tbl = @t_name'),
('@col = @c_name;'),
('FETCH NEXT FROM cur INTO @t_name'),
('END;'),
('CLOSE cur;'),
('DEALLOCATE cur;'),
('SELECT *'),
('FROM #tmp_null_counts'),
('WHERE NullCount > 0'),
('ORDER BY TableName'),
('DROP TABLE #tmp_null_counts;'),
('END;'),
('GO'),
('EXEC GetExactNullCounts ''AdventureWorks2025'';');
