CREATE TABLE "mytable" (
  "-- ======================= PRIMARY KEY UNIQUENESS ======================== --" text NULL
);

INSERT INTO "mytable" ("-- ======================= PRIMARY KEY UNIQUENESS ======================== --")
VALUES
('-- ======================= MY SQL ============================ --'),
('DROP PROCEDURE IF EXISTS VerifyPrimaryKeyUniqueness;'),
('DELIMITER $$'),
('CREATE PROCEDURE VerifyPrimaryKeyUniqueness(IN db_name VARCHAR(255))'),
('BEGIN'),
('DROP TABLE IF EXISTS tmp_pk_counts;'),
('CREATE TEMPORARY TABLE tmp_pk_counts ('),
('table_name VARCHAR(255)'),
('total_rows BIGINT'),
('distinct_pk_rows BIGINT'),
('duplicate_count BIGINT'),
(');'),
('BEGIN'),
('DECLARE done INT DEFAULT FALSE;'),
('DECLARE t_name VARCHAR(255);'),
('DECLARE pk_expr TEXT;'),
(NULL),
('DECLARE cur CURSOR FOR'),
('SELECT'),
('TABLE_NAME'),
('GROUP_CONCAT(CONCAT(''COALESCE(`'''),
('FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE'),
('WHERE TABLE_SCHEMA = db_name'),
('AND CONSTRAINT_NAME = ''PRIMARY'''),
('AND TABLE_NAME IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''errorlog'''),
(')'),
('GROUP BY TABLE_NAME;'),
(NULL),
('DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;'),
('OPEN cur;'),
('read_loop: LOOP'),
('FETCH cur INTO t_name'),
('IF done THEN'),
('LEAVE read_loop;'),
('END IF;'),
('-- Note: MySQL COUNT(DISTINCT col1'),
('SET @sql = CONCAT('),
('''INSERT INTO tmp_pk_counts '''),
('''SELECT \'''''),
('''COUNT(*) - COUNT(DISTINCT '''),
('''FROM `'''),
(');'),
(NULL),
('PREPARE stmt FROM @sql;'),
('EXECUTE stmt;'),
('DEALLOCATE PREPARE stmt;'),
('END LOOP;'),
('CLOSE cur;'),
('END;'),
('SELECT table_name AS TableName'),
('FROM tmp_pk_counts'),
('ORDER BY table_name;'),
(NULL),
('DROP TABLE IF EXISTS tmp_pk_counts;'),
('END$$'),
('DELIMITER ;'),
('CALL VerifyPrimaryKeyUniqueness(''adventureworks2025'');'),
('-- ========================= MS SQL ================================= --');
