CREATE TABLE "mytable" (
  "-- ========================= REFERENTIAL INTEGRITY ========================== --" text NULL
);

INSERT INTO "mytable" ("-- ========================= REFERENTIAL INTEGRITY ========================== --")
VALUES
('-- ============================= MY SQL ===============================--'),
('DROP PROCEDURE IF EXISTS VerifyReferentialIntegrity;'),
('DELIMITER $$'),
('CREATE PROCEDURE VerifyReferentialIntegrity(IN db_name VARCHAR(255))'),
('BEGIN'),
('DROP TABLE IF EXISTS tmp_orphan_counts;'),
('CREATE TEMPORARY TABLE tmp_orphan_counts ('),
('constraint_name VARCHAR(255)'),
('child_table VARCHAR(255)'),
('child_columns TEXT'),
('parent_table VARCHAR(255)'),
('parent_columns TEXT'),
('orphan_count BIGINT'),
(');'),
('BEGIN'),
('DECLARE done INT DEFAULT FALSE;'),
('DECLARE c_name VARCHAR(255);'),
('DECLARE ch_table VARCHAR(255);'),
('DECLARE pr_table VARCHAR(255);'),
('DECLARE join_expr TEXT;'),
('DECLARE null_check_expr TEXT;'),
(NULL),
('-- Safely combines composite foreign keys into a single dynamic execution pass'),
('DECLARE cur CURSOR FOR'),
('SELECT'),
('CONSTRAINT_NAME'),
('TABLE_NAME'),
('REFERENCED_TABLE_NAME'),
('GROUP_CONCAT(CONCAT(''c.`'''),
('GROUP_CONCAT(CONCAT(''p.`'''),
('FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE'),
('WHERE TABLE_SCHEMA = db_name'),
('AND REFERENCED_TABLE_NAME IS NOT NULL'),
('AND TABLE_NAME IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''errorlog'''),
(')'),
('GROUP BY CONSTRAINT_NAME'),
(NULL),
('DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;'),
('OPEN cur;'),
('read_loop: LOOP'),
('FETCH cur INTO c_name'),
('IF done THEN'),
('LEAVE read_loop;'),
('END IF;'),
('-- Dynamically queries orphans across child and parent table layouts'),
('SET @sql = CONCAT('),
('''INSERT INTO tmp_orphan_counts '''),
('''SELECT \'''''),
('''FROM `'''),
('''LEFT JOIN `'''),
('''WHERE '''),
(');'),
(NULL),
('PREPARE stmt FROM @sql;'),
('EXECUTE stmt;'),
('DEALLOCATE PREPARE stmt;'),
('END LOOP;'),
('CLOSE cur;'),
('END;'),
('-- Adjusted condition to >= 0 so you see confirmation logs for successfully passed tables'),
('SELECT constraint_name AS ConstraintName'),
('child_table AS ChildTable'),
('parent_table AS ParentTable'),
('orphan_count AS OrphanCount'),
('FROM tmp_orphan_counts'),
('WHERE orphan_count >= 0'),
('ORDER BY child_table;'),
(NULL),
('DROP TABLE IF EXISTS tmp_orphan_counts;'),
('END$$'),
('DELIMITER ;'),
('CALL VerifyReferentialIntegrity(''adventureworks2025'');'),
('-- ============================ POSTGRES SQL =============================== --'),
('DO $$'),
('DECLARE'),
('r RECORD;'),
('sql_query TEXT;'),
('BEGIN'),
('CREATE TEMP TABLE IF NOT EXISTS tmp_orphan_counts ('),
('constraint_name TEXT'),
('child_table TEXT'),
('parent_table TEXT'),
('orphan_count BIGINT'),
(') ON COMMIT DROP;'),
('FOR r IN'),
('SELECT'),
('tc.constraint_name'),
('tc.table_schema || ''.'' || tc.table_name AS child_table'),
('ccu.table_schema || ''.'' || ccu.table_name AS parent_table'),
('-- Formats composite structural joins correctly for Postgres execution'),
('string_agg(''c."'' || kcu.column_name || ''" = p."'' || ccu.column_name || ''"'''),
('string_agg(''p."'' || ccu.column_name || ''" IS NULL'''),
('FROM information_schema.table_constraints tc'),
('JOIN information_schema.key_column_usage kcu'),
('ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema'),
('JOIN information_schema.constraint_column_usage ccu'),
('ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema'),
('WHERE tc.constraint_type = ''FOREIGN KEY'''),
('AND replace(lower(tc.table_schema || ''_'' || tc.table_name)'),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''errorlog'''),
(')'),
('GROUP BY tc.constraint_name'),
('LOOP'),
('sql_query := ''INSERT INTO tmp_orphan_counts '' ||'),
('''SELECT '' || quote_literal(r.constraint_name) || '''),
('''FROM '' || r.child_table || '' c LEFT JOIN '' || r.parent_table || '' p ON '' || r.join_expr || '' '' ||'),
('''WHERE '' || r.null_expr || '';'';'),
('EXECUTE sql_query;'),
('END LOOP;'),
('END $$;'),
('SELECT constraint_name AS ConstraintName'),
('FROM tmp_orphan_counts'),
('WHERE orphan_count >= 0'),
('ORDER BY child_table;'),
('DROP PROCEDURE IF EXISTS verifyreferentialintegrity(varchar);'),
('-- ============================= MS SERVER  ============================= --'),
('CREATE OR ALTER PROCEDURE VerifyReferentialIntegrity'),
('AS'),
('BEGIN'),
('SET NOCOUNT ON;'),
('IF OBJECT_ID(''tempdb..#tmp_orphan_counts'') IS NOT NULL'),
('DROP TABLE #tmp_orphan_counts;'),
('CREATE TABLE #tmp_orphan_counts ('),
('constraint_name VARCHAR(255)'),
('child_table VARCHAR(255)'),
('parent_table VARCHAR(255)'),
('orphan_count BIGINT'),
(');'),
('DECLARE @fk_name VARCHAR(255)'),
('DECLARE @join_expr NVARCHAR(MAX)'),
('DECLARE cur CURSOR LOCAL FAST_FORWARD FOR'),
('SELECT'),
('fk.name AS constraint_name'),
('''['' + OBJECT_SCHEMA_NAME(fk.parent_object_id) + ''].['' + OBJECT_NAME(fk.parent_object_id) + '']'' AS child_table'),
('''['' + OBJECT_SCHEMA_NAME(fk.referenced_object_id) + ''].['' + OBJECT_NAME(fk.referenced_object_id) + '']'' AS parent_table'),
('STRING_AGG(''c.['' + cp.name + ''] = p.['' + rc.name + '']'''),
('STRING_AGG(''p.['' + rc.name + ''] IS NULL'''),
('FROM sys.foreign_keys fk'),
('INNER JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id'),
('INNER JOIN sys.columns cp ON fkc.parent_object_id = cp.object_id AND fkc.parent_column_id = cp.column_id'),
('INNER JOIN sys.columns rc ON fkc.referenced_object_id = rc.object_id AND fkc.referenced_column_id = rc.column_id'),
('WHERE CONCAT(OBJECT_SCHEMA_NAME(fk.parent_object_id)'),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''dbo_awbuildversion'''),
(')'),
('GROUP BY fk.name'),
('OPEN cur;'),
('FETCH NEXT FROM cur INTO @fk_name'),
('WHILE @@FETCH_STATUS = 0'),
('BEGIN'),
('SET @sql = ''INSERT INTO #tmp_orphan_counts '' +'),
('''SELECT '''''' + @fk_name + '''''''),
('''FROM '' + @child_tbl + '' c LEFT JOIN '' + @parent_tbl + '' p ON '' + @join_expr + '' '' +'),
('''WHERE '' + @null_expr;'),
('EXEC sp_executesql @sql;'),
('FETCH NEXT FROM cur INTO @fk_name'),
('END;'),
('CLOSE cur;'),
('DEALLOCATE cur;'),
('SELECT constraint_name AS ConstraintName'),
('FROM #tmp_orphan_counts'),
('WHERE orphan_count >= 0'),
('ORDER BY child_table;'),
('DROP TABLE #tmp_orphan_counts;'),
('END;'),
('GO'),
('EXEC VerifyReferentialIntegrity;'),
('DROP PROCEDURE IF EXISTS VerifyReferentialIntegrity;');
