CREATE TABLE "mytable" (
  "-- Microsoft SQL Server (T-SQL) : Schema-wise row counts" text
);

INSERT INTO "mytable" ("-- Microsoft SQL Server (T-SQL) : Schema-wise row counts")
VALUES
('-- ============ SALES =========================='),
('SELECT ''Sales.SalesOrderDetail'' AS table_name'),
('SELECT ''Sales.SalesOrderHeader'''),
('SELECT ''Sales.SalesOrderHeaderSalesReason'''),
('SELECT ''Sales.Customer'''),
('SELECT ''Sales.PersonCreditCard'''),
('SELECT ''Sales.CreditCard'''),
('SELECT ''Sales.CurrencyRate'''),
('SELECT ''Sales.Store'''),
('SELECT ''Sales.SpecialOfferProduct'''),
('SELECT ''Sales.SalesPersonQuotaHistory'''),
('SELECT ''Sales.CountryRegionCurrency'''),
('SELECT ''Sales.Currency'''),
('SELECT ''Sales.SalesTaxRate'''),
('SELECT ''Sales.SalesPerson'''),
('SELECT ''Sales.SalesTerritoryHistory'''),
('SELECT ''Sales.SpecialOffer'''),
('SELECT ''Sales.SalesReason'''),
('SELECT ''Sales.SalesTerritory'''),
('SELECT ''Sales.ShoppingCartItem'''),
('-- ========================= PRODUCTION ========================='),
('SELECT ''Production.TransactionHistory'''),
('SELECT ''Production.TransactionHistoryArchive'''),
('SELECT ''Production.WorkOrder'''),
('SELECT ''Production.WorkOrderRouting'''),
('SELECT ''Production.BillOfMaterials'''),
('SELECT ''Production.ProductInventory'''),
('SELECT ''Production.ProductDescription'''),
('SELECT ''Production.ProductModelProductDescriptionCulture'''),
('SELECT ''Production.Product'''),
('SELECT ''Production.ProductProductPhoto'''),
('SELECT ''Production.ProductCostHistory'''),
('SELECT ''Production.ProductListPriceHistory'''),
('SELECT ''Production.ProductModel'''),
('SELECT ''Production.ProductPhoto'''),
('SELECT ''Production.UnitMeasure'''),
('SELECT ''Production.ProductSubcategory'''),
('SELECT ''Production.ProductDocument'''),
('SELECT ''Production.ScrapReason'''),
('SELECT ''Production.Location'''),
('SELECT ''Production.Document'''),
('SELECT ''Production.Culture'''),
('SELECT ''Production.ProductModelIllustration'''),
('SELECT ''Production.Illustration'''),
('SELECT ''Production.ProductReview'''),
('SELECT ''Production.ProductCategory'''),
('-- ========================= PERSON ========================='),
('SELECT ''Person.PersonPhone'''),
('SELECT ''Person.EmailAddress'''),
('SELECT ''Person.Password'''),
('SELECT ''Person.Person'''),
('SELECT ''Person.BusinessEntityAddress'''),
('SELECT ''Person.BusinessEntity'''),
('SELECT ''Person.Address'''),
('SELECT ''Person.BusinessEntityContact'''),
('SELECT ''Person.CountryRegion'''),
('SELECT ''Person.StateProvince'''),
('SELECT ''Person.ContactType'''),
('SELECT ''Person.AddressType'''),
('SELECT ''Person.PhoneNumberType'''),
('-- ========================= PURCHASING ========================='),
('SELECT ''Purchasing.PurchaseOrderDetail'''),
('SELECT ''Purchasing.PurchaseOrderHeader'''),
('SELECT ''Purchasing.ProductVendor'''),
('SELECT ''Purchasing.Vendor'''),
('SELECT ''Purchasing.ShipMethod'''),
('-- ========================= HUMANRESOURCES ========================='),
('SELECT ''HumanResources.EmployeePayHistory'''),
('SELECT ''HumanResources.EmployeeDepartmentHistory'''),
('SELECT ''HumanResources.Employee'''),
('SELECT ''HumanResources.Department'''),
('SELECT ''HumanResources.JobCandidate'''),
('SELECT ''HumanResources.Shift'''),
('-- ==================  MySQL ===================================='),
('SELECT COUNT(*) AS count FROM humanresources_department;  -- 16'),
('SELECT COUNT(*) AS count FROM humanresources_employee;  -- 290'),
('SELECT COUNT(*) AS count FROM humanresources_employeedepartmenthistory;  -- 296'),
('SELECT COUNT(*) AS count FROM humanresources_employeepayhistory;  -- 316'),
('SELECT COUNT(*) AS count FROM humanresources_jobcandidate;  -- 13'),
('SELECT COUNT(*) AS count FROM humanresources_shift;  -- 3'),
('SELECT COUNT(*) AS count FROM person_address;  -- 19614'),
('SELECT COUNT(*) AS count FROM person_addresstype;  -- 6'),
('SELECT COUNT(*) AS count FROM person_businessentity;  -- 20777'),
('SELECT COUNT(*) AS count FROM person_businessentityaddress;  -- 19614'),
('SELECT COUNT(*) AS count FROM person_businessentitycontact;  -- 909'),
('SELECT COUNT(*) AS count FROM person_contacttype;  -- 20'),
('SELECT COUNT(*) AS count FROM person_countryregion;  -- 238'),
('SELECT COUNT(*) AS count FROM person_emailaddress;  -- 19972'),
('SELECT COUNT(*) AS count FROM person_password;  -- 19972'),
('SELECT COUNT(*) AS count FROM person_person;  -- 19972'),
('SELECT COUNT(*) AS count FROM person_personphone;  -- 19972'),
('SELECT COUNT(*) AS count FROM person_phonenumbertype;  -- 3'),
('SELECT COUNT(*) AS count FROM person_stateprovince;  -- 181'),
('SELECT COUNT(*) AS count FROM production_billofmaterials;   -- 2679'),
('SELECT COUNT(*) AS count FROM production_culture;  -- 8'),
('SELECT COUNT(*) AS count FROM production_document;  -- 12'),
('SELECT COUNT(*) AS count FROM production_illustration;   -- 5'),
('SELECT COUNT(*) AS count FROM production_location;  -- 14'),
('SELECT COUNT(*) AS count FROM production_product;  -- 504'),
('SELECT COUNT(*) AS count FROM production_productcategory;  -- 4'),
('SELECT COUNT(*) AS count FROM production_productcosthistory;  -- 395'),
('SELECT COUNT(*) AS count FROM production_productdescription;  -- 762'),
('SELECT COUNT(*) AS count FROM production_productdocument;  -- 32'),
('SELECT COUNT(*) AS count FROM production_productinventory;  -- 1069'),
('SELECT COUNT(*) AS count FROM production_productlistpricehistory;  -- 395'),
('SELECT COUNT(*) AS count FROM production_productmodel;  -- 128'),
('SELECT COUNT(*) AS count FROM production_productmodelillustration;  -- 7'),
('SELECT COUNT(*) AS count FROM production_productmodelproductdescriptionculture;  -- 762'),
('SELECT COUNT(*) AS count FROM production_productphoto;  -- 101'),
('SELECT COUNT(*) AS count FROM production_productproductphoto;  -- 504'),
('SELECT COUNT(*) AS count FROM production_productreview;  -- 4'),
('SELECT COUNT(*) AS count FROM production_productsubcategory;  -- 37'),
('SELECT COUNT(*) AS count FROM production_scrapreason;  -- 16'),
('SELECT COUNT(*) AS count FROM production_transactionhistory;  -- 113443'),
('SELECT COUNT(*) AS count FROM production_transactionhistoryarchive;  -- 89253'),
('SELECT COUNT(*) AS count FROM production_unitmeasure;  -- 38'),
('SELECT COUNT(*) AS count FROM production_workorder;  -- 72591'),
('SELECT COUNT(*) AS count FROM production_workorderrouting;  -- 67131'),
('SELECT COUNT(*) AS count FROM purchasing_productvendor;  -- 460'),
('SELECT COUNT(*) AS count FROM purchasing_purchaseorderdetail;  -- 8845'),
('SELECT COUNT(*) AS count FROM purchasing_purchaseorderheader;  -- 4012'),
('SELECT COUNT(*) AS count FROM purchasing_shipmethod;  -- 5'),
('SELECT COUNT(*) AS count FROM purchasing_vendor;  -- 104'),
('SELECT COUNT(*) AS count FROM sales_countryregioncurrency;  -- 109'),
('SELECT COUNT(*) AS count FROM sales_creditcard;  -- 19118'),
('SELECT COUNT(*) AS count FROM sales_currency;  -- 105'),
('SELECT COUNT(*) AS count FROM sales_currencyrate;  -- 13532'),
('SELECT COUNT(*) AS count FROM sales_customer;  -- 19820'),
('SELECT COUNT(*) AS count FROM sales_personcreditcard;  -- 19118'),
('SELECT COUNT(*) AS count FROM sales_salesterritoryhistory;  -- 17'),
('SELECT COUNT(*) AS count FROM sales_salesorderdetail;   -- 121317'),
('SELECT COUNT(*) AS count FROM sales_salesorderheader;  -- 31465'),
('SELECT COUNT(*) AS count FROM sales_salesorderheadersalesreason;  -- 27647'),
('SELECT COUNT(*) AS count FROM sales_salesperson;  -- 17'),
('SELECT COUNT(*) AS count FROM sales_salespersonquotahistory;  -- 163'),
('SELECT COUNT(*) AS count FROM sales_salesreason;  -- 10'),
('SELECT COUNT(*) AS count FROM sales_salestaxrate;  -- 29'),
('SELECT COUNT(*) AS count FROM sales_salesterritory;  -- 10'),
('SELECT COUNT(*) AS count FROM sales_shopping_cart_item;  -- 3'),
('SELECT COUNT(*) AS count FROM sales_specialoffer;  -- 16'),
('SELECT COUNT(*) AS count FROM sales_specialofferproduct;   -- 538'),
('SELECT COUNT(*) AS count FROM sales_store;  -- 701'),
('-- ================== POSTGRES ========================'),
('-- ========================= SALES ========================='),
('SELECT ''Sales.SalesOrderDetail'' AS table_name'),
('SELECT ''Sales.SalesOrderHeader'''),
('SELECT ''Sales.SalesOrderHeaderSalesReason'''),
('SELECT ''Sales.Customer'''),
('SELECT ''Sales.PersonCreditCard'''),
('SELECT ''Sales.CreditCard'''),
('SELECT ''Sales.CurrencyRate'''),
('SELECT ''Sales.Store'''),
('SELECT ''Sales.SpecialOfferProduct'''),
('SELECT ''Sales.SalesPersonQuotaHistory'''),
('SELECT ''Sales.CountryRegionCurrency'''),
('SELECT ''Sales.Currency'''),
('SELECT ''Sales.SalesTaxRate'''),
('SELECT ''Sales.SalesPerson'''),
('SELECT ''Sales.SalesTerritoryHistory'''),
('SELECT ''Sales.SpecialOffer'''),
('SELECT ''Sales.SalesReason'''),
('SELECT ''Sales.SalesTerritory'''),
('SELECT ''Sales.ShoppingCartItem'''),
('-- ========================= PRODUCTION ========================='),
('SELECT ''Production.TransactionHistory'''),
('SELECT ''Production.TransactionHistoryArchive'''),
('SELECT ''Production.WorkOrder'''),
('SELECT ''Production.WorkOrderRouting'''),
('SELECT ''Production.BillOfMaterials'''),
('SELECT ''Production.ProductInventory'''),
('SELECT ''Production.ProductDescription'''),
('SELECT ''Production.ProductModelProductDescriptionCulture'''),
('SELECT ''Production.Product'''),
('SELECT ''Production.ProductProductPhoto'''),
('SELECT ''Production.ProductCostHistory'''),
('SELECT ''Production.ProductListPriceHistory'''),
('SELECT ''Production.ProductModel'''),
('SELECT ''Production.ProductPhoto'''),
('SELECT ''Production.UnitMeasure'''),
('SELECT ''Production.ProductSubcategory'''),
('SELECT ''Production.ProductDocument'''),
('SELECT ''Production.ScrapReason'''),
('SELECT ''Production.Location'''),
('SELECT ''Production.Document'''),
('SELECT ''Production.Culture'''),
('SELECT ''Production.ProductModelIllustration'''),
('SELECT ''Production.Illustration'''),
('SELECT ''Production.ProductReview'''),
('SELECT ''Production.ProductCategory'''),
('-- ========================= PERSON ========================'),
('SELECT ''Person.PersonPhone'''),
('SELECT ''Person.EmailAddress'''),
('SELECT ''Person.Password'''),
('SELECT ''Person.Person'''),
('SELECT ''Person.BusinessEntityAddress'''),
('SELECT ''Person.BusinessEntity'''),
('SELECT ''Person.Address'''),
('SELECT ''Person.BusinessEntityContact'''),
('SELECT ''Person.CountryRegion'''),
('SELECT ''Person.StateProvince'''),
('SELECT ''Person.ContactType'''),
('SELECT ''Person.AddressType'''),
('SELECT ''Person.PhoneNumberType'''),
('-- ========================= PURCHASING ========================='),
('SELECT ''Purchasing.PurchaseOrderDetail'''),
('SELECT ''Purchasing.PurchaseOrderHeader'''),
('SELECT ''Purchasing.ProductVendor'''),
('SELECT ''Purchasing.Vendor'''),
('SELECT ''Purchasing.ShipMethod'''),
('-- ========================= HUMANRESOURCES ========================='),
('SELECT ''HumanResources.EmployeePayHistory'''),
('SELECT ''HumanResources.EmployeeDepartmentHistory'''),
('SELECT ''HumanResources.Employee'''),
('SELECT ''HumanResources.Department'''),
('SELECT ''HumanResources.JobCandidate'''),
('SELECT ''HumanResources.Shift''');
