CREATE TABLE "mytable" (
  "-- ================== SUM AGGREGATION ============================" text NULL
);

INSERT INTO "mytable" ("-- ================== SUM AGGREGATION ============================")
VALUES
('-- ==================== MY SQL ==============================='),
('DELIMITER $$'),
('CREATE PROCEDURE GetCompleteVerificationMatrix(IN db_name VARCHAR(255))'),
('BEGIN'),
('DROP TABLE IF EXISTS tmp_verification_matrix;'),
('CREATE TEMPORARY TABLE tmp_verification_matrix ('),
('TableName VARCHAR(255)'),
('ColumnName VARCHAR(255)'),
('ColumnSum DECIMAL(38'),
(');'),
('BEGIN'),
('DECLARE done INT DEFAULT FALSE;'),
('DECLARE t_name VARCHAR(255);'),
('DECLARE c_name VARCHAR(255);'),
(NULL),
('DECLARE cur CURSOR FOR'),
('SELECT TABLE_NAME'),
('FROM INFORMATION_SCHEMA.COLUMNS'),
('WHERE TABLE_SCHEMA = db_name'),
('AND DATA_TYPE IN (''int'''),
('AND TABLE_NAME IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''errorlog'''),
(');'),
(NULL),
('DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;'),
('OPEN cur;'),
('read_loop: LOOP'),
('FETCH cur INTO t_name'),
('IF done THEN'),
('LEAVE read_loop;'),
('END IF;'),
('SET @sql = CONCAT('),
('''INSERT INTO tmp_verification_matrix '''),
('''SELECT \'''''),
('''COALESCE(SUM(CAST(`'''),
('''FROM `'''),
(');'),
(NULL),
('PREPARE stmt FROM @sql;'),
('EXECUTE stmt;'),
('DEALLOCATE PREPARE stmt;'),
('END LOOP;'),
('CLOSE cur;'),
('END;'),
('SELECT TableName'),
('FROM tmp_verification_matrix'),
('ORDER BY TableName'),
(NULL),
('DROP TABLE IF EXISTS tmp_verification_matrix;'),
('END$$'),
('DELIMITER ;'),
('CALL GetCompleteVerificationMatrix(''adventureworks2025'');'),
('DROP PROCEDURE IF EXISTS GetCompleteVerificationMatrix;'),
('-- ================================ POSTGRES SQL =========================================='),
('DO $$'),
('DECLARE'),
('r RECORD;'),
('v_sql TEXT;'),
('BEGIN'),
('-- 1. Create temporary table explicitly'),
('CREATE TEMP TABLE IF NOT EXISTS pg_verification_matrix ('),
('table_name TEXT'),
('column_name TEXT'),
('column_sum NUMERIC(38'),
(');'),
('-- Clear any old data if the table already existed in your current session'),
('TRUNCATE TABLE pg_verification_matrix;'),
('FOR r IN'),
('SELECT c.table_schema'),
('FROM information_schema.columns c'),
('JOIN information_schema.tables t ON c.table_name = t.table_name AND c.table_schema = t.table_schema'),
('WHERE t.table_type = ''BASE TABLE'''),
('AND c.data_type IN (''integer'''),
('AND (c.table_schema || ''_'' || c.table_name) IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''humanresources_department'''),
('''production_document'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''errorlog'''),
(')'),
('LOOP'),
('v_sql := format(''INSERT INTO pg_verification_matrix SELECT %L'),
('r.table_name'),
('EXECUTE v_sql;'),
('END LOOP;'),
('END $$;'),
('-- 2. Display results ordered identically to MS SQL'),
('SELECT table_name AS TableName'),
('FROM pg_verification_matrix'),
('ORDER BY table_name'),
('-- 3. Clean up and drop the table immediately after reading the results'),
('DROP TABLE IF EXISTS pg_verification_matrix;'),
('-- ================================== MS SQL ==========================================='),
('CREATE OR ALTER PROCEDURE GetCompleteVerificationMatrix'),
('@db_name SYSNAME'),
('AS'),
('BEGIN'),
('SET NOCOUNT ON;'),
('IF OBJECT_ID(''tempdb..#tmp_verification_matrix'') IS NOT NULL'),
('DROP TABLE #tmp_verification_matrix;'),
('CREATE TABLE #tmp_verification_matrix ('),
('TableName SYSNAME'),
('ColumnName SYSNAME'),
('ColumnSum DECIMAL(38'),
(');'),
('DECLARE @t_name SYSNAME;'),
('DECLARE @c_name SYSNAME;'),
('DECLARE @sql NVARCHAR(MAX);'),
('DECLARE cur CURSOR FOR'),
('SELECT TABLE_NAME'),
('FROM INFORMATION_SCHEMA.COLUMNS'),
('WHERE TABLE_CATALOG = @db_name'),
('AND DATA_TYPE IN (''int'''),
('AND TABLE_NAME IN ('),
('''sales_salesorderdetail'''),
('''production_workorder'''),
('''sales_salesorderheadersalesreason'''),
('''person_password'''),
('''person_businessentity'''),
('''sales_currencyrate'''),
('''production_billofmaterials'''),
('''production_productdescription'''),
('''sales_store'''),
('''purchasing_productvendor'''),
('''humanresources_employeepayhistory'''),
('''humanresources_employee'''),
('''sales_salespersonquotahistory'''),
('''sales_currency'''),
('''production_productsubcategory'''),
('''person_contacttype'''),
('''production_scrapreason'''),
('''production_location'''),
('''sales_salesreason'''),
('''production_productmodelillustration'''),
('''purchasing_shipmethod'''),
('''humanresources_shift'''),
('''awbuildversion'''),
(');'),
('OPEN cur;'),
('FETCH NEXT FROM cur INTO @t_name'),
('WHILE @@FETCH_STATUS = 0'),
('BEGIN'),
('SET @sql = N'''),
('INSERT INTO #tmp_verification_matrix (TableName'),
('SELECT'),
(''''''' + @t_name + '''''''),
(''''''' + @c_name + '''''''),
('COALESCE(SUM(CAST('' + QUOTENAME(@c_name) + '' AS DECIMAL(38'),
('FROM '' + QUOTENAME(@db_name) + ''.dbo.'' + QUOTENAME(@t_name) + '';'';'),
('EXEC sp_executesql @sql;'),
('FETCH NEXT FROM cur INTO @t_name'),
('END;'),
('CLOSE cur;'),
('DEALLOCATE cur;'),
('SELECT *'),
('FROM #tmp_verification_matrix'),
('ORDER BY TableName'),
(NULL),
('END;'),
('GO'),
('EXEC GetCompleteVerificationMatrix ''AdventureWorks2025'';'),
('DROP TABLE #tmp_verification_matrix;');
